# Generated by Django 2.1.5 on 2019-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Targeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('dbid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Targeting_interest',
            },
        ),
    ]
